# Generated by Django 2.1.7 on 2019-03-30 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snitch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourse',
            old_name='stud',
            new_name='stude',
        ),
    ]
