# Generated by Django 2.1.7 on 2019-03-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snitch', '0002_auto_20190330_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='stude',
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]
