# Generated by Django 2.1.7 on 2019-03-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snitch', '0006_auto_20190328_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='stud',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('Android', 'Android'), ('Python', 'Python')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
